"""
GitHub Repository Scanner for AI-related content.

Uses the GitHub API instead of cloning — faster, no disk usage, no permissions issues.
Scans README, CONTRIBUTING, AGENTS.md, and commit messages for AI-related keywords.
"""

import json
import time
import re
import base64
import urllib.request
import urllib.error
from pathlib import Path
from typing import Tuple

# AI-related keywords with associated scores (higher = stronger AI indicator)
AI_KEYWORDS = {
    "gpt": 10,
    "copilot": 10,
    "chatgpt": 10,
    "ai-generated": 12,
    "ai generated": 12,
    "openai": 10,
    "claude": 9,
    "gemini": 8,
    "codellama": 9,
    "codegen": 8,
    "anthropic": 8,
    "ollama": 8,
    "vertexai": 8,
    "autogenerated": 10,
    "generated by": 9,
    "ai-assisted": 9,
    "ai assisted": 9,
    "llm": 8,
    "transformers": 7,
    "langchain": 8,
    "huggingface": 7,
    "mistral": 8,
    "llama": 8,          
    "cursor": 7,
    "devin": 8,
    "codewhisperer": 9,
}

# Threshold score to flag a repo as AI-related
AI_SCORE_THRESHOLD = 15

# Files to fetch and scan from each repo (in addition to README)
EXTRA_FILES_TO_SCAN = [
    "CONTRIBUTING.md",
    "CONTRIBUTING.rst",
    "AGENTS.md",
    "CODEOWNERS",
    ".github/CONTRIBUTING.md",
    ".github/copilot-instructions.md",
]

# GitHub API token (optional but strongly recommended — 60 req/hr without, 5000 with)
# Set via environment variable: export GITHUB_TOKEN=ghp_xxxx
import os
# GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")

class GitHubAPIScanner:
    def __init__(self, repos_json_path: str, output_json_path: str):
        self.repos_json_path = repos_json_path
        self.output_json_path = output_json_path
        self.results = []
        self.request_count = 0

    def _api_get(self, url: str) -> dict | list | None:
        """Make a GitHub API GET request and return parsed JSON, or None on failure."""
        req = urllib.request.Request(url)
        req.add_header("Accept", "application/vnd.github+json")
        req.add_header("X-GitHub-Api-Version", "2022-11-28")
        if GITHUB_TOKEN:
            req.add_header("Authorization", f"Bearer {GITHUB_TOKEN}")

        try:
            with urllib.request.urlopen(req, timeout=10) as resp:
                self.request_count += 1
                return json.loads(resp.read().decode())
        except urllib.error.HTTPError as e:
            if e.code == 404:
                return None  # file just doesn't exist, that's fine
            if e.code == 403:
                print(f"    Rate limited! Sleeping 60s...")
                time.sleep(60)
                return None
            return None
        except Exception:
            return None

    def scan_text_for_keywords(self, text: str) -> Tuple[int, list[str]]:
        """Scan text for AI-related keywords and return (score, found_keywords)."""
        score = 0
        found_keywords = []
        text_lower = text.lower()

        for keyword, keyword_score in AI_KEYWORDS.items():
            count = len(re.findall(r'\b' + re.escape(keyword) + r'\b', text_lower))
            if count > 0:
                score += keyword_score * count
                if keyword not in found_keywords:
                    found_keywords.append(keyword)

        return score, found_keywords

    def fetch_and_scan_file(self, owner: str, repo: str, path: str) -> Tuple[int, list[str]]:
        """Fetch a single file from GitHub API and scan it. Returns (score, keywords)."""
        url = f"https://api.github.com/repos/{owner}/{repo}/contents/{path}"
        data = self._api_get(url)

        if not data or not isinstance(data, dict):
            return 0, []

        encoding = data.get("encoding", "")
        content_raw = data.get("content", "")

        if encoding == "base64":
            try:
                text = base64.b64decode(content_raw).decode("utf-8", errors="ignore")
            except Exception:
                return 0, []
        else:
            text = content_raw

        score, keywords = self.scan_text_for_keywords(text)
        if score > 0:
            print(f"    {path}({score})", end=" ", flush=True)
        return score, keywords

    def fetch_commits_and_scan(self, owner: str, repo: str) -> Tuple[int, list[str]]:
        """Fetch last 50 commit messages and scan them. Returns (score, keywords)."""
        url = f"https://api.github.com/repos/{owner}/{repo}/commits?per_page=50"
        data = self._api_get(url)

        if not data or not isinstance(data, list):
            return 0, []

        # Concatenate all commit messages
        all_messages = "\n".join(
            c.get("commit", {}).get("message", "") for c in data
        )

        score, keywords = self.scan_text_for_keywords(all_messages)
        if score > 0:
            print(f"    Commits({score})", end=" ", flush=True)
        return score, keywords

    def scan_repo(self, owner: str, repo: str) -> Tuple[int, list[str]]:
        """Scan a single repo via API. Returns (total_score, all_keywords)."""
        total_score = 0
        all_keywords = []

        # Scan README (GitHub API has a dedicated endpoint for this)
        readme_url = f"https://api.github.com/repos/{owner}/{repo}/readme"
        readme_data = self._api_get(readme_url)
        if readme_data and isinstance(readme_data, dict):
            try:
                text = base64.b64decode(readme_data.get("content", "")).decode("utf-8", errors="ignore")
                score, keywords = self.scan_text_for_keywords(text)
                total_score += score
                all_keywords.extend(keywords)
                if score > 0:
                    print(f"    README({score})", end=" ", flush=True)
            except Exception:
                pass

        # Scan extra files (CONTRIBUTING, AGENTS.md, etc.)
        for filepath in EXTRA_FILES_TO_SCAN:
            score, keywords = self.fetch_and_scan_file(owner, repo, filepath)
            total_score += score
            all_keywords.extend(keywords)

        # Scan commit messages
        score, keywords = self.fetch_commits_and_scan(owner, repo)
        total_score += score
        all_keywords.extend(keywords)

        # Small delay between repos to be a polite API citizen
        time.sleep(0.5)

        unique_keywords = list(dict.fromkeys(all_keywords))
        return total_score, unique_keywords

    def run_scan(self):
        """Run the scanning process on all repositories."""
        with open(self.repos_json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        repositories = data.get('repositories', [])

        if not GITHUB_TOKEN:
            print("⚠️  No GITHUB_TOKEN set — limited to 60 requests/hr.")
            print("   Set one with: export GITHUB_TOKEN=ghp_xxxx\n")
        else:
            print(f"✓ Using GitHub token (5000 req/hr limit)\n")

        print(f"Starting API scan of {len(repositories)} repositories...\n")

        for i, repo in enumerate(repositories, 1):
            repo_name = repo.get('name', 'unknown')
            repo_url = repo.get('url', '')

            # Parse owner/repo from name field (format: "owner/repo")
            if '/' in repo_name:
                owner, repo_short = repo_name.split('/', 1)
            else:
                print(f"[{i}/{len(repositories)}] Skipping {repo_name} (can't parse owner/repo)\n")
                continue

            print(f"[{i}/{len(repositories)}] {repo_name}")
            score, keywords = self.scan_repo(owner, repo_short)

            result = {
                "name": repo_name,
                "url": repo_url,
                "score": score,
                "keywords_found": keywords,
                "is_ai_related": score >= AI_SCORE_THRESHOLD,
                "stars": repo.get('stars', 0),
                "language": repo.get('language', 'Unknown'),
                "owner_type": repo.get('owner_type', 'Unknown'),
            }

            self.results.append(result)
            status = "✓ AI-RELATED" if result['is_ai_related'] else ""
            print(f"  → Score: {score} {status}\n")

        # Sort by score descending
        self.results.sort(key=lambda x: x['score'], reverse=True)

        output_data = {
            "scan_metadata": {
                "total_repos_scanned": len(repositories),
                "ai_score_threshold": AI_SCORE_THRESHOLD,
                "ai_related_repos_found": sum(1 for r in self.results if r['is_ai_related']),
                "total_api_requests": self.request_count,
            },
            "repositories": self.results
        }

        with open(self.output_json_path, 'w', encoding='utf-8') as f:
            json.dump(output_data, f, indent=2, ensure_ascii=False)

        print(f"\n{'='*60}")
        print(f"Scan complete! Results saved to: {self.output_json_path}")
        print(f"{'='*60}")
        print(f"Total repos scanned:     {len(repositories)}")
        print(f"AI-related repos found:  {output_data['scan_metadata']['ai_related_repos_found']}")
        print(f"Total API requests made: {self.request_count}")
        print(f"\nTop 10 repos by AI score:")
        for i, result in enumerate(self.results[:10], 1):
            status = "✓ AI" if result['is_ai_related'] else ""
            print(f"  {i}. {result['name']:50} Score: {result['score']:4} {status}")


if __name__ == "__main__":
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    input_file = os.path.join(BASE_DIR, "sample_100.json")
    output_file = "ai_scan_results.json"

    if not Path(input_file).exists():
        print(f"Error: {input_file} not found!")
        exit(1)

    scanner = GitHubAPIScanner(input_file, output_file)
    scanner.run_scan()