"""
GitHub Repository Scanner for AI-related content.

Uses the GitHub API instead of cloning. Scans README, CONTRIBUTING, AGENTS.md,
and commit messages for AI-related keywords and AI commit-trailer disclosures
(Co-Authored-By: Claude, Assisted-by: Copilot, etc.).
"""

import json
import sys
import threading
import time
import re
import base64
import urllib.request
import urllib.error
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Tuple

# cp1252 consoles crash on the emoji in a couple of print statements below.
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# 'cursor'/'devin' are phrase-gated, not bare words: bare 'cursor' matched a
# literal database cursor in one commit, and 'devin' is a common first name.
AI_KEYWORDS = {
    "gpt": 10,
    "copilot": 10,
    "chatgpt": 10,
    "ai-generated": 12,
    "ai generated": 12,
    "openai": 10,
    "claude": 9,
    "gemini": 8,
    "codellama": 9,
    "codegen": 8,
    "anthropic": 8,
    "ollama": 8,
    "vertexai": 8,
    "autogenerated": 10,
    "generated by": 9,
    "ai-assisted": 9,
    "ai assisted": 9,
    "llm": 8,
    "transformers": 7,
    "langchain": 8,
    "huggingface": 7,
    "mistral": 8,
    "llama": 8,
    "cursor ai": 8,
    "cursor agent": 9,
    "using cursor": 6,
    "devin ai": 9,
    "devin.ai": 9,
    "codewhisperer": 9,
}

AI_SCORE_THRESHOLD = 15

# Structured AI coding-agent commit trailers, e.g. "Co-Authored-By: Claude
# <noreply@anthropic.com>" — a much higher-confidence signal than a bare
# keyword mention.
AI_TRAILER_RE = re.compile(
    r'(?:co-authored-by|assisted-by|generated-by|reviewed-by)\s*:\s*'
    r'[^\n<]*?(claude|copilot|cursor(?:\s*agent)?|codex|devin|gemini|chatgpt|'
    r'gpt-\d|anthropic|openai|codewhisperer|amazon\s*q|tabnine|windsurf)',
    re.IGNORECASE,
)
AI_TRAILER_SCORE = 20  # per matching trailer line, > any single keyword

EXTRA_FILES_TO_SCAN = [
    "CONTRIBUTING.md",
    "CONTRIBUTING.rst",
    "AGENTS.md",
    "CODEOWNERS",
    ".github/CONTRIBUTING.md",
    ".github/copilot-instructions.md",
]

# Shared secrets live in WebCrawling/.env (see WebCrawling/.env.example).
import os
try:
    from dotenv import load_dotenv
except ImportError:
    def load_dotenv(*_args, **_kwargs):
        return False

load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'WebCrawling', '.env'))


def _sanitize_github_token(token: str) -> str:
    """Treat placeholder tokens (e.g. '__') as absent — a malformed token
    401s every request, worse than sending none. Real tokens are always
    well over 20 characters."""
    token = (token or "").strip()
    return token if len(token) >= 20 else ""


GITHUB_TOKEN = _sanitize_github_token(os.environ.get("GITHUB_TOKEN", ""))

MAX_WORKERS = 6  # concurrent repo scans


class GitHubAPIScanner:
    def __init__(self, repos_json_path: str, output_json_path: str):
        self.repos_json_path = repos_json_path
        self.output_json_path = output_json_path
        self.results = []
        self.request_count = 0
        self.rate_limited_hits = 0
        self._lock = threading.Lock()
        self._exhausted = threading.Event()      # primary hourly quota confirmed at 0
        self._token_invalid = threading.Event()  # GitHub 401'd the configured token

    def _api_get(self, url: str, retry_on_rate_limit: bool = True,
                 allow_token: bool = True) -> dict | list | None:
        """
        GET a GitHub API URL, return parsed JSON or None on failure.

        A primary rate-limit hit (X-RateLimit-Remaining: 0) won't clear for
        up to an hour, so the first time it's seen we set a shared flag and
        every call short-circuits instantly instead of retrying doomed
        requests. A secondary (burst) limit usually clears in under a
        minute, so that case gets one wait-and-retry.
        """
        if self._exhausted.is_set():
            return None

        use_token = GITHUB_TOKEN and allow_token and not self._token_invalid.is_set()

        req = urllib.request.Request(url)
        req.add_header("Accept", "application/vnd.github+json")
        req.add_header("X-GitHub-Api-Version", "2022-11-28")
        if use_token:
            req.add_header("Authorization", f"Bearer {GITHUB_TOKEN}")

        with self._lock:
            self.request_count += 1

        try:
            with urllib.request.urlopen(req, timeout=10) as resp:
                return json.loads(resp.read().decode())
        except urllib.error.HTTPError as e:
            if e.code == 404:
                return None
            if e.code == 401:
                if use_token:
                    self._report_invalid_token()
                    return self._api_get(url, retry_on_rate_limit=retry_on_rate_limit, allow_token=False)
                return None
            if e.code == 403:
                with self._lock:
                    self.rate_limited_hits += 1
                remaining = e.headers.get("X-RateLimit-Remaining") if e.headers else None
                if remaining == "0":
                    self._report_exhausted(e.headers)
                    return None
                if retry_on_rate_limit:
                    print("    Secondary rate limit hit, waiting 30s...")
                    time.sleep(30)
                    return self._api_get(url, retry_on_rate_limit=False)
            return None
        except Exception:
            return None

    def _report_exhausted(self, headers) -> None:
        """One-time warning + shared flag once the primary quota hits 0."""
        with self._lock:
            if self._exhausted.is_set():
                return
            self._exhausted.set()
            reset_at = headers.get("X-RateLimit-Reset") if headers else None
            reset_note = ""
            if reset_at:
                try:
                    reset_note = f" — resets at {time.strftime('%H:%M:%S', time.localtime(int(reset_at)))}"
                except ValueError:
                    pass
            print(
                f"\n{'!' * 60}\n"
                f"GitHub API rate limit EXHAUSTED after {self.request_count} requests{reset_note}.\n"
                f"Remaining repos will be skipped (not scanned) rather than hang\n"
                f"retrying doomed requests. Set a real GITHUB_TOKEN in\n"
                f"WebCrawling/.env (5000/hr instead of 60/hr) and re-run.\n"
                f"{'!' * 60}\n"
            )

    def _report_invalid_token(self) -> None:
        """One-time warning + shared flag once GitHub rejects the token."""
        with self._lock:
            if self._token_invalid.is_set():
                return
            self._token_invalid.set()
            masked = f"{GITHUB_TOKEN[:8]}...{GITHUB_TOKEN[-4:]}" if len(GITHUB_TOKEN) > 12 else "***"
            print(
                f"\n{'!' * 60}\n"
                f"GITHUB_TOKEN was REJECTED by GitHub (401 Bad Credentials): {masked}\n"
                f"It looks like a real token but is expired, revoked, or wrong.\n"
                f"Falling back to UNAUTHENTICATED requests (60/hr) for the rest\n"
                f"of this run — check/regenerate the token in WebCrawling/.env.\n"
                f"{'!' * 60}\n"
            )

    def scan_text_for_keywords(self, text: str) -> Tuple[int, list[str], int]:
        """Returns (score, found_keywords, trailer_count)."""
        score = 0
        found_keywords = []
        text_lower = text.lower()

        for keyword, keyword_score in AI_KEYWORDS.items():
            count = len(re.findall(r'\b' + re.escape(keyword) + r'\b', text_lower))
            if count > 0:
                score += keyword_score * count
                if keyword not in found_keywords:
                    found_keywords.append(keyword)

        trailer_matches = AI_TRAILER_RE.findall(text)
        trailer_count = len(trailer_matches)
        score += trailer_count * AI_TRAILER_SCORE

        return score, found_keywords, trailer_count

    def fetch_and_scan_file(self, owner: str, repo: str, path: str, log: list) -> Tuple[int, list[str], int]:
        url = f"https://api.github.com/repos/{owner}/{repo}/contents/{path}"
        data = self._api_get(url)

        if not data or not isinstance(data, dict):
            return 0, [], 0

        encoding = data.get("encoding", "")
        content_raw = data.get("content", "")

        if encoding == "base64":
            try:
                text = base64.b64decode(content_raw).decode("utf-8", errors="ignore")
            except Exception:
                return 0, [], 0
        else:
            text = content_raw

        score, keywords, trailers = self.scan_text_for_keywords(text)
        if score > 0:
            log.append(f"{path}({score})")
        return score, keywords, trailers

    def fetch_commits_and_scan(self, owner: str, repo: str, log: list) -> Tuple[int, list[str], int]:
        url = f"https://api.github.com/repos/{owner}/{repo}/commits?per_page=50"
        data = self._api_get(url)

        if not data or not isinstance(data, list):
            return 0, [], 0

        all_messages = "\n".join(
            c.get("commit", {}).get("message", "") for c in data
        )

        score, keywords, trailers = self.scan_text_for_keywords(all_messages)
        if score > 0:
            log.append(f"Commits({score})" + (f" [{trailers} AI trailer(s)]" if trailers else ""))
        return score, keywords, trailers

    def scan_repo(self, owner: str, repo: str) -> dict:
        log: list = []
        breakdown = {"readme": 0, "extra_files": 0, "commits": 0}
        all_keywords = []
        total_trailers = 0

        readme_url = f"https://api.github.com/repos/{owner}/{repo}/readme"
        readme_data = self._api_get(readme_url)
        if readme_data and isinstance(readme_data, dict):
            try:
                text = base64.b64decode(readme_data.get("content", "")).decode("utf-8", errors="ignore")
                score, keywords, trailers = self.scan_text_for_keywords(text)
                breakdown["readme"] = score
                all_keywords.extend(keywords)
                total_trailers += trailers
                if score > 0:
                    log.append(f"README({score})")
            except Exception:
                pass

        for filepath in EXTRA_FILES_TO_SCAN:
            score, keywords, trailers = self.fetch_and_scan_file(owner, repo, filepath, log)
            breakdown["extra_files"] += score
            all_keywords.extend(keywords)
            total_trailers += trailers

        score, keywords, trailers = self.fetch_commits_and_scan(owner, repo, log)
        breakdown["commits"] = score
        all_keywords.extend(keywords)
        total_trailers += trailers

        unique_keywords = list(dict.fromkeys(all_keywords))
        total_score = breakdown["readme"] + breakdown["extra_files"] + breakdown["commits"]

        return {
            "score": total_score,
            "score_breakdown": breakdown,
            "keywords_found": unique_keywords,
            "ai_trailer_count": total_trailers,
            "log": log,
        }

    def _scan_one(self, index: int, total: int, repo: dict) -> dict:
        """Runs inside a thread pool worker; scans one repo and returns its result."""
        repo_name = repo.get('name', 'unknown')
        repo_url = repo.get('url', '')

        if '/' not in repo_name:
            print(f"[{index}/{total}] Skipping {repo_name} (can't parse owner/repo)\n")
            return {
                "name": repo_name, "url": repo_url, "score": 0,
                "keywords_found": [], "is_ai_related": False,
                "stars": repo.get('stars', 0), "language": repo.get('language', 'Unknown'),
                "owner_type": repo.get('owner_type', 'Unknown'),
                "skipped": "can't parse owner/repo",
            }

        if self._exhausted.is_set():
            print(f"[{index}/{total}] {repo_name} — skipped (rate limit exhausted)\n")
            return {
                "name": repo_name, "url": repo_url, "score": 0,
                "keywords_found": [], "is_ai_related": False,
                "stars": repo.get('stars', 0), "language": repo.get('language', 'Unknown'),
                "owner_type": repo.get('owner_type', 'Unknown'),
                "scan_status": "skipped_rate_limited",
            }

        owner, repo_short = repo_name.split('/', 1)
        scan = self.scan_repo(owner, repo_short)
        became_exhausted_mid_scan = self._exhausted.is_set()

        print(f"[{index}/{total}] {repo_name}")
        if scan["log"]:
            print("    " + " ".join(scan["log"]))
        status = "✓ AI-RELATED" if scan["score"] >= AI_SCORE_THRESHOLD else ""
        trailer_note = f" [{scan['ai_trailer_count']} AI co-author trailer(s)]" if scan["ai_trailer_count"] else ""
        exhausted_note = " [RATE LIMITED MID-SCAN — likely incomplete]" if became_exhausted_mid_scan else ""
        print(f"  → Score: {scan['score']} {status}{trailer_note}{exhausted_note}\n")

        result = {
            "name": repo_name,
            "url": repo_url,
            "score": scan["score"],
            "score_breakdown": scan["score_breakdown"],
            "keywords_found": scan["keywords_found"],
            "ai_trailer_count": scan["ai_trailer_count"],
            "is_ai_related": scan["score"] >= AI_SCORE_THRESHOLD,
            "stars": repo.get('stars', 0),
            "language": repo.get('language', 'Unknown'),
            "owner_type": repo.get('owner_type', 'Unknown'),
        }
        if became_exhausted_mid_scan:
            result["scan_status"] = "incomplete_rate_limited"
        return result

    def _save_incremental(self):
        """Write progress to disk after each repo — crash-safe."""
        sorted_results = sorted(self.results, key=lambda x: x['score'], reverse=True)
        metadata = {
            "total_repos_scanned": len(self.results),
            "ai_score_threshold": AI_SCORE_THRESHOLD,
            "ai_related_repos_found": sum(1 for r in self.results if r.get('is_ai_related')),
            "total_api_requests": self.request_count,
            "rate_limit_hits": self.rate_limited_hits,
        }
        if self._token_invalid.is_set():
            metadata["token_warning"] = (
                "GITHUB_TOKEN in WebCrawling/.env was rejected by GitHub (401 "
                "Bad Credentials) — it looks like a real token but is "
                "expired/revoked/wrong. This run fell back to unauthenticated "
                "requests (60/hr) after that was detected."
            )
        if self._exhausted.is_set():
            incomplete = [r['name'] for r in self.results if r.get('scan_status') in
                          ('skipped_rate_limited', 'incomplete_rate_limited')]
            metadata["warning"] = (
                "GitHub API rate limit was exhausted during this run. Repos "
                "below are NOT a reliable 'no AI signal found' result, they "
                "simply weren't scanned — check each repo's scan_status field."
            )
            metadata["repos_affected_by_rate_limit"] = incomplete
        output_data = {
            "scan_metadata": metadata,
            "repositories": sorted_results,
        }
        try:
            tmp = self.output_json_path + '.tmp'
            with open(tmp, 'w', encoding='utf-8') as f:
                json.dump(output_data, f, indent=2, ensure_ascii=False)
            os.replace(tmp, self.output_json_path)
        except Exception as e:
            print(f"    (incremental save failed: {e})")

    def _check_remaining_quota(self) -> int | None:
        """Upfront /rate_limit check so a low-quota run warns before scanning
        instead of the user finding out from an all-zeros result file."""
        req = urllib.request.Request("https://api.github.com/rate_limit")
        req.add_header("Accept", "application/vnd.github+json")
        if GITHUB_TOKEN:
            req.add_header("Authorization", f"Bearer {GITHUB_TOKEN}")
        try:
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = json.loads(resp.read().decode())
                return data.get("resources", {}).get("core", {}).get("remaining")
        except urllib.error.HTTPError as e:
            if e.code == 401 and GITHUB_TOKEN:
                self._report_invalid_token()
                return self._check_remaining_quota_unauthenticated()
            return None
        except Exception:
            return None

    def _check_remaining_quota_unauthenticated(self) -> int | None:
        req = urllib.request.Request("https://api.github.com/rate_limit")
        req.add_header("Accept", "application/vnd.github+json")
        try:
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = json.loads(resp.read().decode())
                return data.get("resources", {}).get("core", {}).get("remaining")
        except Exception:
            return None

    def run_scan(self):
        with open(self.repos_json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        repositories = data.get('repositories', [])
        needed = len(repositories) * 8  # README + 6 extra files + commits, worst case

        if not GITHUB_TOKEN:
            print(" No GITHUB_TOKEN set (or it's a placeholder) — limited to 60 requests/hr.")
            print("   Set a real one in WebCrawling/.env: GITHUB_TOKEN=ghp_xxxx\n")
        else:
            print(f"✓ Using GitHub token (5000 req/hr limit)\n")

        remaining = self._check_remaining_quota()
        if remaining is not None:
            print(f"Rate limit: {remaining} requests remaining this window "
                  f"(this scan needs up to {needed} for {len(repositories)} repos)")
            if remaining < needed:
                print(f" Likely not enough headroom to finish — expect the run to stop "
                      f"early with a rate-limit warning below.\n")
            else:
                print()

        print(f"Starting API scan of {len(repositories)} repositories "
              f"({MAX_WORKERS} concurrent)...\n")

        total = len(repositories)
        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
            futures = {
                executor.submit(self._scan_one, i, total, repo): repo
                for i, repo in enumerate(repositories, 1)
            }
            for future in as_completed(futures):
                try:
                    result = future.result()
                except Exception as e:
                    repo = futures[future]
                    print(f"  ✗ Error scanning {repo.get('name', 'unknown')}: {e}\n")
                    continue
                with self._lock:
                    self.results.append(result)
                    self._save_incremental()

        self.results.sort(key=lambda x: x['score'], reverse=True)
        self._save_incremental()

        ai_related_count = sum(1 for r in self.results if r.get('is_ai_related'))
        trailer_repos = sum(1 for r in self.results if r.get('ai_trailer_count'))

        print(f"\n{'='*60}")
        print(f"Scan complete! Results saved to: {self.output_json_path}")
        print(f"{'='*60}")
        print(f"Total repos scanned:            {len(self.results)}")
        print(f"AI-related repos found:         {ai_related_count}")
        print(f"Repos with AI co-author trailers: {trailer_repos}")
        print(f"Total API requests made:        {self.request_count}")
        if self._exhausted.is_set():
            affected = sum(1 for r in self.results
                            if r.get('scan_status') in ('skipped_rate_limited', 'incomplete_rate_limited'))
            print(f"\n RATE LIMIT EXHAUSTED partway through this run — {affected} repo(s) "
                  f"were skipped or only partially scanned.")
            print(f"   Their scores are NOT reliable 'no AI signal' results — see each repo's ")
            print(f"   scan_status field, and scan_metadata.warning in the output JSON.")
            print(f"   Set a real GITHUB_TOKEN in WebCrawling/.env and re-run for complete results.")
        print(f"\nTop 10 repos by AI score:")
        for i, result in enumerate(self.results[:10], 1):
            status = "✓ AI" if result.get('is_ai_related') else ""
            print(f"  {i}. {result['name']:50} Score: {result['score']:4} {status}")


if __name__ == "__main__":
    import argparse

    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    parser = argparse.ArgumentParser(description="Keyword + AI-trailer scan of a repo sample")
    parser.add_argument('--input', default=os.path.join(BASE_DIR, "sample.json"))
    parser.add_argument('--output', default=os.path.join(BASE_DIR, "ai_scan_results.json"))
    args = parser.parse_args()

    if not Path(args.input).exists():
        print(f"Error: {args.input} not found!")
        exit(1)

    scanner = GitHubAPIScanner(args.input, args.output)
    scanner.run_scan()
